CREATE TABLE "estado" (
    "id"	NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome"	VARCHAR2(255) NOT NULL
);

CREATE TABLE "cidade" (
    "id"	NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome"	VARCHAR2(255) NOT NULL,
    "estado_id"	NUMBER NOT NULL,
    FOREIGN KEY("estado_id") REFERENCES "estado"("id")
);

CREATE TABLE "pessoa" (
    "id"	NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome"	VARCHAR2(255) NOT NULL,
    "sexo"	CHAR(1) NOT NULL,
    "data_nascimento" DATE NOT NULL,
    "cidade_id"	NUMBER NOT NULL,
    FOREIGN KEY("cidade_id") REFERENCES "cidade"("id")
);

CREATE TABLE "post" (
    "id"	NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "titulo"	VARCHAR2(255) NOT NULL,
    "conteudo"	CLOB NOT NULL,
    "data_hora_publicacao" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "data_hora_atualizacao" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "likes"	NUMBER DEFAULT 0 NOT NULL,
    "dislikes" NUMBER DEFAULT 0 NOT NULL,
    "visualizacoes" NUMBER DEFAULT 0 NOT NULL,
    "nota_post" NUMBER DEFAULT 0.0 NOT NULL,
    "pessoa_id" NUMBER NOT NULL,
    FOREIGN KEY("pessoa_id") REFERENCES "pessoa"("id")
);

CREATE TABLE "comentario" (
    "id"	NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "conteudo"	CLOB NOT NULL,
    "data_hora" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "pessoa_id" NUMBER NOT NULL,
    "post_id"	NUMBER NOT NULL,
    FOREIGN KEY("pessoa_id") REFERENCES "pessoa"("id"),
    FOREIGN KEY("post_id") REFERENCES "post"("id")
);

CREATE TABLE "categoria" (
    "id"	NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome"	VARCHAR2(255) NOT NULL
);

CREATE TABLE "post_categoria" (
    "id"	NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "categoria_id"	NUMBER NOT NULL,
    "post_id"	NUMBER NOT NULL,
    FOREIGN KEY("categoria_id") REFERENCES "categoria"("id"),
    FOREIGN KEY("post_id") REFERENCES "post"("id")
);

