INSERT INTO estado (nome) VALUES ('Acre');
INSERT INTO estado (nome) VALUES ('Alagoas');
INSERT INTO estado (nome) VALUES ('Amapá');
INSERT INTO estado (nome) VALUES ('Amazonas');
INSERT INTO estado (nome) VALUES ('Bahia');
INSERT INTO estado (nome) VALUES ('Ceará');
INSERT INTO estado (nome) VALUES ('Espírito Santo');
INSERT INTO estado (nome) VALUES ('Goiás');
INSERT INTO estado (nome) VALUES ('Maranhão');
INSERT INTO estado (nome) VALUES ('Mato Grosso');
INSERT INTO estado (nome) VALUES ('Mato Grosso do Sul');
INSERT INTO estado (nome) VALUES ('Minas Gerais');
INSERT INTO estado (nome) VALUES ('Pará');
INSERT INTO estado (nome) VALUES ('Paraíba');
INSERT INTO estado (nome) VALUES ('Paraná');
INSERT INTO estado (nome) VALUES ('Pernambuco');
INSERT INTO estado (nome) VALUES ('Piauí');
INSERT INTO estado (nome) VALUES ('Rio de Janeiro');
INSERT INTO estado (nome) VALUES ('Rio Grande do Norte');
INSERT INTO estado (nome) VALUES ('Rio Grande do Sul');
INSERT INTO estado (nome) VALUES ('Rondônia');
INSERT INTO estado (nome) VALUES ('Roraima');
INSERT INTO estado (nome) VALUES ('Santa Catarina');
INSERT INTO estado (nome) VALUES ('São Paulo');
INSERT INTO estado (nome) VALUES ('Sergipe');
INSERT INTO estado (nome) VALUES ('Tocantins');
INSERT INTO estado (nome) VALUES ('Distrito Federal');

